version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: node
      POSTGRES_PASSWORD: node
      POSTGRES_DB: cube
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api: &api
    depends_on:
      - postgres
    build: .
    ports:
      - 3000:3000
    environment: &api_environment
      NODE_ENV: production
      DATABASE_URL: postgresql://node:node@postgres:5432/cube?schema=public
      JWT_SECRET: abcde
      MIGRATE_DATABASE: 1
    command: npm run start
    volumes:
      - .:/app

  studio:
    <<: *api
    ports:
      - 5555:5555
    environment:
      <<: *api_environment
      MIGRATE_DATABASE: 0
    command: npx prisma studio

volumes:
  postgres_data:
