version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: node
      POSTGRES_PASSWORD: node
      POSTGRES_DB: cube
    volumes:
      - data:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080

  api:
    build: .
    ports:
      - 3000:3000 # API
      - 5555:5555 # Prisma Studio
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://node:node@postgres:5432/cube?schema=public
    command: npm run serve
    volumes:
      - .:/app


volumes:
  data:
