version: '3.7'

services:
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: node
      POSTGRES_PASSWORD: node
      POSTGRES_DB: cube
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api: &api
    depends_on:
      - postgres
    build: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://node:node@postgres:5432/cube
    env_file:
      - .env
    command: npm run start

  studio:
    <<: *api
    ports:
      - 5555:5555
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://node:node@postgres:5432/cube
    command: npx prisma studio

volumes:
  postgres_data:
