name: build

on:
  workflow_run:
    workflows: [test]
    types: [completed]
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/cube-ttrb
          username: nologin
          password: ${{ secrets.SCW_REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: rg.fr-par.scw.cloud/cube-ttrb/api:latest
          cache-from: type=registry,ref=rg.fr-par.scw.cloud/cube-ttrb/api:buildcache
          cache-to: type=registry,ref=rg.fr-par.scw.cloud/cube-ttrb/api:buildcache,mode=max
